binary_cnn/urls.py
from django.urls import path
from . import views


app_name = 'binary_cnn'
urlpatterns = [
    path('', views.home, name='home'),
    path('start/', views.start, name="start"),
    path('datasets/', views.datasets, name="datasets"),
    path('datasets/add/', views.add_dataset, name="add_dataset"),
    path('datasets/delete/', views.delete_datasets, name="delete_datasets"),
    path('models/', views.models, name="models"),
    path('model/<int:model_id>', views.model, name="model"),
    path('models/delete/', views.delete_models, name="delete_models"),
    path('create/', views.create, name="create"),
    path('train/<int:model_id>', views.train, name="train"),
    path('classify_form/', views.classify_form, name='classify_form'),
    path('classify_result/<int:image_id>/', views.classify_result, name='classify_result.html'),
]

image_classifier/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('binary_cnn.urls')),
]

binary_cnn/forms.py
from .models import Dataset, DSCategory, BinaryModel, TrainConfig, Image
from django import forms
from django.utils.translation import gettext_lazy as _


class DatasetForm(forms.ModelForm):
    class Meta:
        model = Dataset
        fields = ['save_dir', 'class_labels', 'type', 'input_shape', 'category']
        labels = {'save_dir': '', 'class_labels': 'labels', 'type': 'Type', 'input_shape': 'Shape',
                  'category': 'Category'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Exclude labels from all fields
        for field_name in self.fields:
            self.fields[field_name].label = False

        self.fields['class_labels'].widget.attrs['placeholder'] = _('labels')
        self.fields['type'].widget.attrs['placeholder'] = _('type')
        self.fields['input_shape'].widget.attrs['placeholder'] = _('shape:  e.g  300, 300, 3')
        self.fields['category'].widget.attrs['placeholder'] = _('category')


class BinaryModelForm(forms.ModelForm):
    class Meta:
        model = BinaryModel
        fields = ['name', 'description']
        labels = {'name': 'Name', 'description': 'Description'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Exclude labels from all fields
        for field_name in self.fields:
            self.fields[field_name].label = False

        # Optionally, you can set placeholders for the fields instead of labels
        self.fields['name'].widget.attrs['placeholder'] = _('Name')
        self.fields['description'].widget.attrs['placeholder'] = _('Description')


class TrainConfigForm(forms.ModelForm):

    class Meta:
        model = TrainConfig
        fields = ['training_ds', 'validation_ds', 'learning_rate', 'minimum_accuracy', 'num_of_batches',
                  'num_of_epochs', 'training_ds', 'validation_ds']
        labels = {'training_ds': 'Training', 'validation_ds': 'Validation'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['training_ds'].queryset = Dataset.objects.filter(category=DSCategory.TRAINING)
        self.fields['validation_ds'].queryset = Dataset.objects.filter(category=DSCategory.VALIDATION)
        self.fields['learning_rate'].widget.attrs['placeholder'] = _('learning rate: e.g 0.001')
        self.fields['minimum_accuracy'].widget.attrs['placeholder'] = _('min accuracy: e.g 0.99')
        self.fields['num_of_batches'].widget.attrs['placeholder'] = _('number of batches: e.g 8')
        self.fields['num_of_epochs'].widget.attrs['placeholder'] = _('number of epochs:  e.g  15')


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['img_file']
        labels = {'img_file': ''}

binary_cnn/views.py
import os
import json
import pickle
import zipfile

import keras
from django.db.models import ProtectedError
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

import binary_cnn.ml_cnn as ml
from binary_cnn.forms import DatasetForm, BinaryModelForm, TrainConfigForm, ImageForm
from binary_cnn.models import DSType, DSCategory, Dataset, Status, BinaryModel, Image, TrainConfig, TrainingKpi
import binary_cnn.utilities as util


def home(request):
    return render(request, 'binary_cnn/home.html')


def start(request):
    return render(request, 'binary_cnn/get_started.html')


def datasets(request):
    # Get all datasets - order by date.
    context = {'datasets': Dataset.objects.order_by('-date_added')}
    return render(request, 'binary_cnn/datasets.html', context)


def add_dataset(request):
    if request.method != 'POST':
        # No data submitted, create a blank form.
        form = DatasetForm()
    else:
        # POST data submitted; process data.
        form = DatasetForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_dataset = form.save(commit=False)
            try:
                # Set dataset's name equal to file name - minus ext.
                ds_name = new_dataset.save_dir.name.split('.')[0]
                new_dataset.name = ds_name
                new_dataset.save()

                # Extract zip from the default tmp folder to dataset root dir.
                zip_ref = zipfile.ZipFile(new_dataset.save_dir, 'r')
                ds_root = new_dataset.save_dir.name.split('tmp')[0]+new_dataset.name
                zip_ref.extractall(ds_root)
                zip_ref.close()

                # Update the dataset's save_dir to point to the dataset root dir.
                new_dataset.save_dir = ds_root
                new_dataset.save()

            except zipfile.BadZipFile:
                new_dataset.delete()
                raise ValueError("The file is not a valid zip file.")
            except Exception as e:
                print(f"Error adding dataset : {e}")
            finally:
                # clear tmp folder.
                util.rm_files('binary_cnn/datasets/tmp')

        return redirect('binary_cnn:datasets')

    context = {'form': form}
    return render(request, 'binary_cnn/add_dataset.html', context)


def delete_datasets(request):
    json_data_str = request.POST.get('json')
    json_data = json.loads(json_data_str)
    ids = json_data.get('ids')

    for ds_id in ids:
        try:
            dataset = Dataset.objects.get(id=ds_id)
            dataset.delete()
        except ProtectedError as error:
            print(f"Error: {error}")
            error_msg = "Error: Cannot delete a dataset that is 'in use'"
            return JsonResponse({'error_type': "ProtectedError", 'error_msg': error_msg}, status=400)
        except Dataset.DoesNotExist:
            print(f"Dataset {ds_id} does not exist")

    # Return json.
    data = {'msg': 'Datasets deleted!'}
    return JsonResponse(data)


def models(request):
    # Get all the trained models.
    binary_models = BinaryModel.objects.order_by('-date_added')
    context = {'binary_models': binary_models}
    return render(request, 'binary_cnn/models.html', context)


def model(request, model_id):
    try:
        # Get the requested model
        binary_model = BinaryModel.objects.get(id=model_id)
        train_config = None
        training_kpis = None
        if binary_model.status == Status.TRAINED:
            train_config = TrainConfig.objects.get(binary_model=binary_model)
            training_kpis = TrainingKpi.objects.get(config=train_config)
        context = {'binary_model': binary_model, 'train_config': train_config, 'training_kpis': training_kpis}
        return render(request, 'binary_cnn/model.html', context)
    except BinaryModel.DoesNotExist:
        # Handle the case where the object does not exist
        print("Object does not exist")
    return redirect('binary_cnn:models')


def delete_models(request):
    json_data_str = request.POST.get('json')
    json_data = json.loads(json_data_str)
    ids = json_data.get('ids')

    for model_id in ids:
        try:
            binary_model = BinaryModel.objects.get(id=model_id)

            # If the model is trained then check if its ds is 'in-use' after delete.
            if binary_model.status == Status.TRAINED:

                # Get a reference to datasets associated with the model via TrainConfig.
                train_config = TrainConfig.objects.get(binary_model=model_id)
                ds_used_by_model = [train_config.training_ds, train_config.validation_ds]

                # Delete model causing cascade delete to the related TrainConfig.
                # NB. A dataset is 'in use' iff it is associated with at least one TrainConfig.
                binary_model.delete()

                # Check if the datasets are still 'in use'.
                for ds in ds_used_by_model:
                    ds.is_active = is_dataset_in_use(ds)
                    ds.save()
            else:
                binary_model.delete()

        except BinaryModel.DoesNotExist:
            print("BinaryModel does not exist")

    # Return json.
    data = {'msg': 'Models deleted!'}
    return JsonResponse(data)


def is_dataset_in_use(dataset):
    # If a dataset is related to one or more TrainConfig then it's still 'in use'.
    tcs_using_ds_for_training = TrainConfig.objects.filter(training_ds=dataset.id)
    tcs_using_ds_for_validation = TrainConfig.objects.filter(validation_ds=dataset.id)

    num_tcs_using_ds = len(tcs_using_ds_for_training) + len(tcs_using_ds_for_validation)

    if num_tcs_using_ds == 0:
        return False
    else:
        return True


def create(request):
    if request.method != 'POST':
        create_form = BinaryModelForm()
        context = {'create_form': create_form}
        return render(request, 'binary_cnn/create.html', context)
    else:
        create_form = BinaryModelForm(data=request.POST)

        # Ensures all fields are fill out etc.
        if create_form.is_valid():
            # Create a new instance of BinaryModel.
            new_bm = create_form.save(commit=False)

            # Create a machine learning model (i.e. tensorflow)
            ml_model = ml.create_model()

            # Save the ml model to 'save_dir' of the BinaryModel instances.
            path = os.path.join(new_bm.save_dir, new_bm.name)
            ml_model.save(path)

            # Create a dir for the models static content.
            static_dir_path = os.path.join('static', new_bm.name)
            static_dir_rel_path = os.path.join('binary_cnn', static_dir_path)
            os.mkdir(static_dir_rel_path)

            # Redirect tf model's summary print output to the file.
            fname = 'model_summary.txt'
            with open(os.path.join(static_dir_rel_path, fname), 'w') as f:
                ml_model.summary(print_fn=lambda x: f.write(x + '\n'))

            # Add the absolute path to the BinaryModel static content - required for clean-up!
            new_bm.static_dir_path = os.getcwd() + '/' + static_dir_rel_path

            # Commit changes to the db.
            new_bm.save()

            # Return json.
            summary_txt_path = os.path.join('/', static_dir_path, fname)
            msg = f'Success: {new_bm.name} created!'
            data = {'model_id': new_bm.id, 'model_summary_txt': summary_txt_path, 'msg': msg}
            return JsonResponse(data)


def train(request, model_id):
    try:
        binary_model = BinaryModel.objects.get(id=model_id)

        if request.method != 'POST':
            train_form = TrainConfigForm()

        else:
            train_form = TrainConfigForm(data=request.POST)
            # Ensures all fields are fill out etc.
            if train_form.is_valid():

                # If retraining then delete old TrainConfig (BM to TC is 1 to 1)
                if binary_model.status == Status.TRAINED:
                    old_train_config = TrainConfig.objects.get(binary_model=model_id)

                    # Get a reference to datasets associated with the old TrainConfig.
                    ds_used_by_tc = [old_train_config.training_ds, old_train_config.validation_ds]

                    # Delete the old config and update the model status.
                    old_train_config.delete()
                    binary_model.status = Status.UNTRAINED
                    binary_model.save()

                    # NB, We've deleted tc above before checking if ds is still 'in use'.
                    # This is intentional as we look up tcs to see if they have ref to any ds.
                    for ds in ds_used_by_tc:
                        ds.is_active = is_dataset_in_use(ds)
                        ds.save()

                    # Also for retraining we must remove previous history.pkl.
                    path_history_file = os.path.join(binary_model.static_dir_path, 'history.pkl')

                    if os.path.exists(path_history_file):
                        os.remove(path_history_file)

                # Create a new TrainingConfig instance.
                train_config = train_form.save(commit=False)

                # Load the model
                saved_model_path = binary_model.save_dir + '/' + binary_model.name
                ml_model = keras.models.load_model(saved_model_path)

                # Compile the model
                ml_model = ml.compile_model(ml_model)

                # Update the model's status
                binary_model.status = Status.TRAINING
                binary_model.save()

                # Get the datasets references for training and validation.
                training_dataset = train_config.training_ds
                validation_dataset = train_config.validation_ds

                # Get the dir path from the references.

binary_cnn/templates/binary_cnn/add_dataset.html
{% extends "binary_cnn/base.html" %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
         #nn_img {
        position: absolute;
        width: 120px;
        height: 80px;
        padding-left: 0px;
        padding-bottom: 0px;
        border: 0px solid red;
      }
      #nn_svg_box {
        width: 420px;
        height: 90px;
        padding-left: 0px;
        border: 0px solid green;
    }
      #title {
        position: absolute;
        padding-top: 20px;
        width: 300px;
        padding-left: 120px;
        font-size: 30px;
        border: 0px solid blue;
    }
    </style>
</head>
<body>
    <main role="main" class="container">
      <div id="nn_svg_box">
        <img id="nn_img" src="/static/svg/neural_network5.svg" alt="SVG Image"><div id="title">Add Dataset</div>
      </div>
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>

    <br> <br>
    <form  class="form" method="post" enctype="multipart/form-data">

      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-sm btn-primary" type="submit">Add</button>
    </form>

    </main>
</body>
{% endblock content %}
</html>

binary_cnn/templates/binary_cnn/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Binary CNN</title>
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
  <style>
        #nn_img {
        position: absolute;
        width: 120px;
        height: 80px;
        padding-left: 0px;
        padding-bottom: 0px;
        border: 0px solid red;
    }
      #nn_svg_box {
        width: 420px;
        height: 90px;
        padding-left: 0px;
        border: 0px solid green;
    }
        #title {
        position: absolute;
        padding-top: 20px;
        width: 300px;
        padding-left: 120px;
        font-size: 30px;
        border: 0px solid blue;
    }
    </style>
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'binary_cnn:home'%}">Home</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'binary_cnn:datasets'%}">Datasets</a>
        </li>
      </ul>
      <ul class="navbar-nav ml">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'binary_cnn:models' %}">Models</a>
        </li>
      </ul>
      <ul class="navbar-nav ml">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'binary_cnn:classify_form' %}">Classify</a>
        </li>
      </ul>
    </div>
  </nav>
  <main role="main" class="container">
        <div>
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>

</html>

binary_cnn/templates/binary_cnn/classify_form.html
{% extends "binary_cnn/base.html" %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Classify form</title>
    <style>
      #nn_img {
        position: absolute;
        width: 120px;
        height: 80px;
        padding-left: 0px;
        padding-bottom: 0px;
        border: 0px solid red;
      }
      #nn_svg_box {
        width: 420px;
        height: 90px;
        padding-left: 0px;
        border: 0px solid green;
      }
      #title {
        position: absolute;
        padding-top: 20px;
        width: 420px;
        padding-left: 120px;
        font-size: 30px;
        border: 0px solid blue;
      }
      #upload-container {
        border: 0px solid blue;
      }
      #upload-img {
        margin-right: 5px;
        border: 0px solid green;
        float: left;
        }
      #upload-btn {
        border: 0px solid red;
        float: left;
        }
        .clearFix:after {
        content: ".";
        display: block;
        height: 0;
        clear: both;
        visibility: hidden;
    }
    </style>
</head>
<body>
  <main role="main" class="container">

  <div id="nn_svg_box">
    <img id="nn_img" src="/static/svg/neural_network5.svg" alt="SVG Image"><div id="title">Classify</div>
  </div>
  <div class="pb-2 mb-2 border-bottom">
    {% block page_header %}{% endblock page_header %}
  </div>

  <br><br>
  <form  method="post" enctype="multipart/form-data">
    <div id="mb-3">

        <div id="upload-container" class="clearFix">
          <label id="upload-img" for="category" class="form-label"><b>Upload an Image:</b></label>
          <div id="upload-btn">
            {% csrf_token %}
            {{ form.as_p }}
          </div>
        </div>

        <label for="category" class="form-label"><b>Select a Model:</b></label>
        <select class="form-select" id="category" name="model_id">
        {% for trained_model in trained_models %}
             <option value="{{trained_model.id}}">{{ trained_model }}</option>
        {% endfor %}
        </select>
        <br>
        <button class="btn-sm btn-primary" type="submit">Classify</button>
      </div>
  </form>
  </main>
</body>
{% endblock content %}

binary_cnn/templates/binary_cnn/classify_result.html
{% extends "binary_cnn/base.html" %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Classify form</title>
</head>
<body>
<div class="jumbotron">
    <h2 class="display-4">Summary</h2>
    <div>
      <div id="update" class="fonts">Image classified as: {{classification}}<div id="result" class="fonts"></div></div><br>
      <img src="/static/{{img_file_name}}" alt="Thumbnail" class="thumbnail">
    </div>
  </div>
</body>
{% endblock content %}

binary_cnn/templates/binary_cnn/create.html
{% extends "binary_cnn/base.html" %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Create</title>
    <style>
       #nn_img {
        position: absolute;
        width: 120px;
        height: 80px;
        padding-left: 0px;
        padding-bottom: 0px;
        border: 0px solid red;
      }
       #nn_svg_box {
        width: 420px;
        height: 90px;
        padding-left: 0px;
        border: 0px solid green;
    }
        #title {
        position: absolute;
        padding-top: 20px;
        width: 300px;
        padding-left: 120px;
        font-size: 30px;
        border: 0px solid blue;
    }
      #buttonContainer {
        margin: 0px;
        width: 250px;
        border: 0px solid blue;
      }
      #back_to_models_button {
        visibility: hidden;
        float: left;
      }
      #train_button {
        visibility: hidden;
        float: right;
      }
      .clearFix:after {
        content: ".";
        display: block;
        height: 0;
        clear: both;
        visibility: hidden;
      }
    </style>
    {% load static %}
    <script src="{% static 'js/create.js' %}" defer></script>
</head>
<body>
  <main role="main" class="container">

    <div id="nn_svg_box">
      <img id="nn_img" src="/static/svg/neural_network5.svg" alt="SVG Image"><div id="title">Create Model</div>
    </div>
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>


  <br><br>
  <form id="create_form" action="/submit" method='post'>
    {% csrf_token %}
    {{ create_form.as_p }}
    <button name="submit" class="btn btn-sm btn-primary" type="submit">Create</button>
  </form>

  <div id="model_created_msg"></div>
  <br>
  <div id="buttonContainer" class="clearFix">
      <form action = "{% url 'binary_cnn:models' %}" method="post" >
          {% csrf_token %}
          <button id="back_to_models_button" class="btn btn-sm btn-secondary">Back to Models</button>
      </form>
      <form>
          <input type="hidden" id="hidden_model_id" name="hidden_model_id" value="">
          <button type="button" id="train_button" class="btn btn-sm btn-primary" onclick="trainRequest()">Train this Model</button>
      </form>
  </div>

  <br>
  <br>
  <div id="arch_summary"><b></b></div>
  <br>
  <pre id="fileContent"></pre>
  </main>
</body>
{% endblock content %}

binary_cnn/templates/binary_cnn/datasets.html
{% extends "binary_cnn/base.html" %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Datasets</title>
    <style>
        #nn_img {
        position: absolute;
        width: 120px;
        height: 80px;
        padding-left: 0px;
        padding-bottom: 0px;
        border: 0px solid red;
    }
      #nn_svg_box {
        width: 420px;
        height: 90px;
        padding-left: 0px;
        border: 0px solid green;
    }
        #title {
        position: absolute;
        padding-top: 20px;
        width: 300px;
        padding-left: 120px;
        font-size: 30px;
        border: 0px solid blue;
    }
        #modelButtonContainer {
        margin: 0px;
        width: 130px;
        border: 0px solid blue;
    }
      #addDatasetButton {
        width: 61px;
        float: right;
    }
      #deleteDatasetButton {
        width: 61px;
        #margin-top; 20px;
        float: left;
        margin-top: 23px;
        border: 1px solid gray;
    }

        #link_create {
            padding: 10px;
            padding-bottom: 40px;
    }
        table {
            border-collapse: collapse;
            #width: 60%;
    }
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
    }
        th {
            background-color: #f2f2f2;
    }
        .status {
            color: green;
            #border: 0px solid green;
    }
        .clearFix:after {
        content: ".";
        display: block;
        height: 0;
        clear: both;
        visibility: hidden;
    }
    </style>
    {% load static %}
    <script src="{% static 'js/datasets.js' %}" defer></script>
</head>
<body>
  <main role="main" class="container">

    <div id="nn_svg_box">
      <img id="nn_img" src="/static/svg/neural_network5.svg" alt="SVG Image"><div id="title">Datasets</div>
    </div>
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>

    <br>
    <div id="modelButtonContainer" class="clearFix">
      <form id="myForm" action="/submit" method="post">
        {% csrf_token %}
        <!-- Other form fields here -->
        <button id="deleteDatasetButton" class="btn btn-sm btn-secondary" type="submit" >Delete</button>
      </form>
      <br>
      <a href="{% url 'binary_cnn:add_dataset' %}"><button class="btn btn-sm btn-primary" id="addDatasetButton">Add</button></a>
    </div>

    <input type="checkbox" onclick="toggleAll(this)"/> Select All<div id="error_msg"></div>
      <div class="card mb-3">
          <table>
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Labels</th>
                    <th>Type</th>
                    <th>Shape</th>
                    <th>Date</th>
                    <th>In use</th>
                </tr>
            </thead>
            <tbody>
                {% for dataset in datasets %}
                <tr>
                    <td><input type="checkbox" class="rowCheckbox" data-id="{{dataset.id}}"/></td>
                    <td>{{ dataset.name }}</td>
                    <td>{{ dataset.category }}</td>
                    <td>[{{ dataset.class_labels }}]</td>
                    <td>{{ dataset.type }}</td>
                    <td>({{ dataset.input_shape }})</td>
                    <td>{{ dataset.date_added|date:'M d, Y H:i'  }}</td>
                    <td>{{ dataset.is_active }}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
      </div>
  </main>
</body>
{% endblock content %}
</html>

binary_cnn/templates/binary_cnn/home.html
{% extends "binary_cnn/base.html" %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <style>
      #nn_img {
        position: absolute;
        width: 120px;
        height: 80px;
        padding-left: 0px;
        padding-bottom: 0px;
        border: 0px solid red;
      }
      #nn_svg_box {
        width: 420px;
        height: 90px;
        padding-left: 0px;
        border: 0px solid green;
      }
      #title {
        position: absolute;
        padding-top: 20px;
        width: 600px;
        padding-left: 120px;
        font-size: 30px;
        border: 0px solid blue;
      }
    </style>
</head>
<body>

  <main role="main" class="container">
    <div id="nn_svg_box">
      <img id="nn_img" src="/static/svg/neural_network5.svg" alt="SVG Image"><div id="title">ML Model Manager</div>
    </div>
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
      <br>
  </main>


    <div class="jumbotron">
      <h1 class="display-4">Machine Learning Model Management.</h1>
      <p class="lead">Create and Manage the lifecycle of your machine learning models. Prepare and upload your datasets. Create a model by choosing a model template and selecting your training parameters. Now put it into action by classifying new images.</p>
      <a class="btn btn-lg btn-primary" href="{% url 'binary_cnn:start' %}" role="button">Get started &raquo;</a>
    </div>


</body>
</html>
{% endblock content %}

binary_cnn/templates/binary_cnn/models.html
{% extends "binary_cnn/base.html" %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Models</title>
    <style>
      #nn_img {
        position: absolute;
        width: 120px;
        height: 80px;
        padding-left: 0px;
        padding-bottom: 0px;
        border: 0px solid red;
      }
      #nn_svg_box {
        width: 420px;
        height: 90px;
        padding-left: 0px;
        border: 0px solid green;
    }
      #title {
        position: absolute;
        padding-top: 20px;
        width: 300px;
        padding-left: 120px;
        font-size: 30px;
        border: 0px solid blue;
    }
      #modelButtonContainer {
        margin: 0px;
        width: 130px;
        border: 0px solid blue;
      }
      #trainModelButton {

        float: right;
        width: 61px;
      }
      #deleteModelButton {

        float: left;
        width: 61px;
        margin-top: 23px;
        border: 1px solid gray;
      }

        #link_create {
            padding: 10px;
            padding-bottom: 40px;
        }
        table {
            border-collapse: collapse;
            #width: 60%;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
        .status {
            color: green;
            #border: 0px solid green;
        }
        .clearFix:after {
        content: ".";
        display: block;
        height: 0;
        clear: both;
        visibility: hidden;
      }
    </style>
    {% load static %}
    <script src="{% static 'js/models.js' %}" defer></script>
</head>
<body>
  <main role="main" class="container">

  <div id="nn_svg_box">
    <img id="nn_img" src="/static/svg/neural_network5.svg" alt="SVG Image"><div id="title">Models</div>
  </div>
  <div class="pb-2 mb-2 border-bottom">
    {% block page_header %}{% endblock page_header %}
  </div>

  <br>
  <div id="modelButtonContainer" class="clearFix">
      <form id="myForm" action="/submit"  method='post'>
        {% csrf_token %}
        <!-- Other form fields here -->
        <button id="deleteModelButton" class="btn btn-sm btn-secondary" type="submit" >Delete</button>
      </form><br>
      <a href="{% url 'binary_cnn:create' %}"><button class="btn btn-sm btn-primary" id="trainModelButton">Create</button></a>
  </div>

  <input type="checkbox" onclick="toggleAll(this)"/> Select All
  <div class="card mb-3">
      <table>
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Template</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% for binary_model in binary_models %}
            <tr>
                <td><input type="checkbox" class="rowCheckbox" data-id="{{binary_model.id}}"/></td>
                <td><a class="nav-link" href="{% url 'binary_cnn:model' binary_model.id %}">{{ binary_model.name }}</a></td>
                <td class="">{{ binary_model.type.value }}</td>
                <td class="status">{{ binary_model.status }}</td>
                <td>{{ binary_model.date_added|date:'M d, Y H:i'  }}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
  </div>
  </main>
</body>
{% endblock content %}
</html>